a = input('digite algo: ')
print('qual o tipo primitivo de a ', type(a))
print('é um numero ? ', a.isnumeric())
print('é uma letra ?', a.isalpha())
print('é alphanumerico ?', a.isalnum())
print('tem espaços ?', a.isspace())
print('esta em maiusculo', a.isupper())
print('esta em minusculo', a.islower())
print('esta capitalizada ?', a.istitle())