nome = input('digite seu nome completo: ').strip()
print('seu nome com letra maiuscula {}'.format(nome.upper()))
print('seu nome com letra minuscula {}'.format(nome.lower()))
print('seu nome contem {} caracteres'.format(len(nome) - nome.count(' ')))
#print('seu primeiro nome tem {} caracteres'.format(nome.find(' ')))
separa = nome.split()
print('seu primeiro nome é {} e ele tem {} letras'.format(separa[0], len(separa[0])))